version: "3.9"

services:
  db:
    container_name: db
    image: postgres
    # ports:
    #   - 5433:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  server:
    container_name: server
    image: food-wiz_backend
    build: ./backend
    volumes:
      - ./app:/usr/src/app/app
      - ./migrations:/usr/src/app/migrations
    ports:
      - 5100:5000
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_NAME=postgres
    depends_on:
      - db

  frontend:
    container_name: frontend
    image: food-wiz_client
    build: ./client
    command: ["npm", "start"]
    ports:
      - 3100:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      # - REACT_APP_BACKEND_URL=http://fvz.env4health.finki.ukim.mk/api
      - REACT_APP_BACKEND_URL=http://localhost:5100/api
    depends_on:
      - server
    stdin_open: true
    tty: true

volumes:
  postgres-data:
