apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { include "server.fullname" . } }
  labels: { { - include "server.labels" . | nindent 4 } }
spec:
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels: { { - include "server.selectorLabels" . | nindent 6 } }
  template:
    metadata:
      labels: { { - include "server.selectorLabels" . | nindent 8 } }
    spec:
      serviceAccountName: { { include "server.serviceAccountName" . } }
      containers:
        - name: { { .Chart.Name } }
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: { { .Values.image.pullPolicy } }
          ports:
            containerPort: 5000
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
