version: "3"

services:
  db:
    container_name: db
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  automation:
    container_name: automation
    image: food-wiz-automation
    build:
      context: ./food-wiz-automation
      dockerfile: Dockerfile
    # volumes:
    #   - ./app:/usr/src/app/app
    ports:
      - 5000:5000
    # environment:
    #   - DB_USER=postgres
    #   - DB_PASSWORD=postgres
    #   - DB_HOST=db
    #   - DB_NAME=postgres
    # depends_on:
    #   - db

  backend:
    container_name: backend
    image: food-wiz-backend
    build:
      context: ./food-wiz-backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - name=value

  client:
    container_name: client
    image: food-wiz-client
    build:
      context: ./food-wiz-client
      dockerfile: Dockerfile
    command: ["npm", "start"]
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      # - REACT_APP_BACKEND_URL=http://fvz.env4health.finki.ukim.mk/api
      - REACT_APP_BACKEND_URL=http://localhost:8080/api
    depends_on:
      - backend
    stdin_open: true
    tty: true

volumes:
  postgres-data:
