"""empty message

Revision ID: 9426e268a613
Revises: 
Create Date: 2022-05-01 17:42:49.479995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9426e268a613'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('annotation_span_document_id_fkey', 'annotation_span', type_='foreignkey')
    op.create_foreign_key(None, 'annotation_span', 'document', ['document_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('annotation_span_dataset_tag_dataset_tag_id_fkey', 'annotation_span_dataset_tag', type_='foreignkey')
    op.drop_constraint('annotation_span_dataset_tag_annotation_span_id_fkey', 'annotation_span_dataset_tag', type_='foreignkey')
    op.create_foreign_key(None, 'annotation_span_dataset_tag', 'annotation_span', ['annotation_span_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'annotation_span_dataset_tag', 'dataset_tag', ['dataset_tag_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('corpus_dataset_dataset_id_fkey', 'corpus_dataset', type_='foreignkey')
    op.drop_constraint('corpus_dataset_corpus_id_fkey', 'corpus_dataset', type_='foreignkey')
    op.create_foreign_key(None, 'corpus_dataset', 'dataset', ['dataset_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'corpus_dataset', 'corpus', ['corpus_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('dataset_tag_dataset_id_fkey', 'dataset_tag', type_='foreignkey')
    op.create_foreign_key(None, 'dataset_tag', 'dataset', ['dataset_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('document_corpus_id_fkey', 'document', type_='foreignkey')
    op.create_foreign_key(None, 'document', 'corpus', ['corpus_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.create_foreign_key('document_corpus_id_fkey', 'document', 'corpus', ['corpus_id'], ['id'])
    op.drop_constraint(None, 'dataset_tag', type_='foreignkey')
    op.create_foreign_key('dataset_tag_dataset_id_fkey', 'dataset_tag', 'dataset', ['dataset_id'], ['id'])
    op.drop_constraint(None, 'corpus_dataset', type_='foreignkey')
    op.drop_constraint(None, 'corpus_dataset', type_='foreignkey')
    op.create_foreign_key('corpus_dataset_corpus_id_fkey', 'corpus_dataset', 'corpus', ['corpus_id'], ['id'])
    op.create_foreign_key('corpus_dataset_dataset_id_fkey', 'corpus_dataset', 'dataset', ['dataset_id'], ['id'])
    op.drop_constraint(None, 'annotation_span_dataset_tag', type_='foreignkey')
    op.drop_constraint(None, 'annotation_span_dataset_tag', type_='foreignkey')
    op.create_foreign_key('annotation_span_dataset_tag_annotation_span_id_fkey', 'annotation_span_dataset_tag', 'annotation_span', ['annotation_span_id'], ['id'])
    op.create_foreign_key('annotation_span_dataset_tag_dataset_tag_id_fkey', 'annotation_span_dataset_tag', 'dataset_tag', ['dataset_tag_id'], ['id'])
    op.drop_constraint(None, 'annotation_span', type_='foreignkey')
    op.create_foreign_key('annotation_span_document_id_fkey', 'annotation_span', 'document', ['document_id'], ['id'])
    # ### end Alembic commands ###
